import CanonicalRoots.CoxExplicitPolynomials
import CanonicalRoots.CoxCandidateMap

noncomputable section
namespace CanonicalRoots
open MvPolynomial

theorem chain_signature_nat {a α β γ : ℕ} (he : ArithmeticTernary a ⟨.IV,α,β,γ⟩) :
    candidateSignature ⟨.IV,α,β,γ⟩ = ![α, γ * (β - 1) + 1, α * (γ - 1)] := by
  have hb : 1 ≤ β := by have hb : 2 ≤ β := he.2.1; omega
  have hc : 1 ≤ γ := by have hc : 2 ≤ γ := he.2.2.1; omega
  ext i
  have hh : (candidateSignature ⟨.IV,α,β,γ⟩ i : ℤ) =
      (![α, γ * (β - 1) + 1, α * (γ - 1)] i : ℕ) := by
    rw [candidateSignature_cast he]
    fin_cases i <;> simp [Cox.signature, Nat.cast_sub hb, Nat.cast_sub hc]
  exact_mod_cast hh

theorem chain_extra_generator_relation {a α β γ : ℕ} (he : ArithmeticTernary a ⟨.IV,α,β,γ⟩) :
    (X (2 : Fin 3) ^ (α * γ) : MvPolynomial (Fin 3) ℂ) +
      candidateMonomial ⟨.IV,α,β,γ⟩ 0 ^ α +
      candidateMonomial ⟨.IV,α,β,γ⟩ 1 ^ (β - 1) * candidateMonomial ⟨.IV,α,β,γ⟩ 2 =
      X 2 ^ α * fermat (candidateSignature ⟨.IV,α,β,γ⟩) := by
  have hc : 1 ≤ γ := by have hc : 2 ≤ γ := he.2.2.1; omega
  have hαγ : α + α * (γ - 1) = α * γ := by
    nlinarith [Nat.sub_add_cancel hc]
  rw [chain_signature_nat he]
  simp [fermat, Fin.sum_univ_three, candidateMonomial_explicit, mul_pow,
    ← pow_mul, pow_succ, mul_add]
  rw [← pow_add, hαγ]
  ring

/-- The extra chain monomial belongs to the subalgebra generated by the three Cox monomials. -/
theorem chain_extra_generator_image {a α β γ : ℕ} (ha : 1 ≤ a)
    (he : ArithmeticTernary a ⟨.IV,α,β,γ⟩)
    (τ : DegreeGroup (candidateSignature ⟨.IV,α,β,γ⟩))
    (hτ : IsCanonicalRoot (candidateSignature ⟨.IV,α,β,γ⟩) a τ) :
    (candidatePolynomialMap ha he τ hτ (-(X 0 ^ α) - X 1 ^ (β - 1) * X 2) :
      AmbientRing (candidateSignature ⟨.IV,α,β,γ⟩)) =
      ambientQuotient (candidateSignature ⟨.IV,α,β,γ⟩) (X 2 ^ (α * γ)) := by
  have hF : ambientQuotient (candidateSignature ⟨.IV,α,β,γ⟩)
      (fermat (candidateSignature ⟨.IV,α,β,γ⟩)) = 0 :=
    Ideal.Quotient.eq_zero_iff_mem.mpr (Ideal.subset_span (Set.mem_singleton _))
  have hh := congrArg (ambientQuotient (candidateSignature ⟨.IV,α,β,γ⟩))
    (chain_extra_generator_relation he)
  simp only [map_add, map_mul, map_pow, hF, mul_zero] at hh
  change ((rootSubalgebra _ τ).val.comp (candidatePolynomialMap ha he τ hτ)) _ = _
  rw [candidatePolynomialMap_val]
  change ambientQuotient _ (aeval (candidateMonomial ⟨.IV,α,β,γ⟩) _) = _
  simp only [map_sub, map_neg, map_pow, map_mul, aeval_X]
  linear_combination -hh

end CanonicalRoots
