import CanonicalRoots.QuotientCotangent

noncomputable section
namespace CanonicalRoots
open MvPolynomial

/-- The ideal generated by the coordinate functions at the origin of the actual quotient. -/
abbrev presentedOriginIdeal {n : ℕ} (f : MvPolynomial (Fin n) ℂ) : Ideal (PresentedRing f) :=
  (polynomialOriginIdeal n).map (Ideal.Quotient.mk (Ideal.span {f}))

theorem presented_ker_le_origin_square {n : ℕ} (f : MvPolynomial (Fin n) ℂ)
    (hf : HasNoConstantOrLinear f) :
    RingHom.ker (Ideal.Quotient.mkₐ ℂ (Ideal.span {f})).toRingHom ≤
      polynomialOriginIdeal n ^ 2 := by
  change RingHom.ker (Ideal.Quotient.mk (Ideal.span {f})) ≤ _
  rw [Ideal.mk_ker, Ideal.span_singleton_le_iff_mem]
  exact (noConstantOrLinear_iff_mem_square f).mp hf

/-- Minimal relations leave every coordinate class independent in the cotangent space. -/
def presentedOriginCotangentEquiv {n : ℕ} (f : MvPolynomial (Fin n) ℂ)
    (hf : HasNoConstantOrLinear f) :
    (presentedOriginIdeal f).Cotangent ≃ₗ[ℂ] (Fin n → ℂ) :=
  (quotientCotangentEquiv (polynomialOriginIdeal n)
    (Ideal.Quotient.mkₐ ℂ (Ideal.span {f})) (Ideal.Quotient.mkₐ_surjective ℂ _)
    (presented_ker_le_origin_square f hf)).symm.trans (polynomialOriginCotangentEquiv n)

theorem presentedOriginCotangent_finrank {n : ℕ} (f : MvPolynomial (Fin n) ℂ)
    (hf : HasNoConstantOrLinear f) :
    Module.finrank ℂ (presentedOriginIdeal f).Cotangent = n := by
  rw [(presentedOriginCotangentEquiv f hf).finrank_eq]
  simp

theorem RootHypersurfacePresentation.cotangent_finrank {n : ℕ} {p : Fin n → ℕ}
    {τ : DegreeGroup p} (H : RootHypersurfacePresentation p τ) :
    Module.finrank ℂ (presentedOriginIdeal H.polynomial).Cotangent = n :=
  presentedOriginCotangent_finrank H.polynomial H.no_constant_or_linear

/-- Evaluation at the origin descends to the presented hypersurface. -/
def presentedAugmentation {n : ℕ} (f : MvPolynomial (Fin n) ℂ) (h0 : f.coeff 0 = 0) :
    PresentedRing f →ₐ[ℂ] ℂ :=
  Ideal.Quotient.liftₐ (Ideal.span {f}) (aeval (fun _ : Fin n => (0 : ℂ))) (by
    change Ideal.span {f} ≤ RingHom.ker (aeval (fun _ : Fin n => (0 : ℂ))).toRingHom
    rw [Ideal.span_singleton_le_iff_mem]
    change aeval (fun _ : Fin n => (0 : ℂ)) f = 0
    simpa [constantCoeff_eq] using h0)

@[simp] theorem presentedAugmentation_mk {n : ℕ} (f : MvPolynomial (Fin n) ℂ)
    (h0 : f.coeff 0 = 0) (g : MvPolynomial (Fin n) ℂ) :
    presentedAugmentation f h0 (Ideal.Quotient.mk (Ideal.span {f}) g) = g.coeff 0 := by
  change aeval (fun _ : Fin n => (0 : ℂ)) g = _
  simp [constantCoeff_eq]

theorem presentedOriginIdeal_eq_ker {n : ℕ} (f : MvPolynomial (Fin n) ℂ)
    (h0 : f.coeff 0 = 0) :
    presentedOriginIdeal f = RingHom.ker (presentedAugmentation f h0).toRingHom := by
  ext z
  obtain ⟨g, rfl⟩ := Ideal.Quotient.mk_surjective z
  constructor
  · intro hz
    obtain ⟨h, hh, heq⟩ := (Ideal.mem_map_iff_of_surjective
      (Ideal.Quotient.mk (Ideal.span {f})) Ideal.Quotient.mk_surjective).mp hz
    change presentedAugmentation f h0 (Ideal.Quotient.mk (Ideal.span {f}) g) = 0
    rw [← heq, presentedAugmentation_mk]
    exact (mem_polynomialOriginIdeal_iff h).mp hh
  · intro hz
    apply Ideal.mem_map_of_mem
    rw [mem_polynomialOriginIdeal_iff]
    exact (presentedAugmentation_mk f h0 g).symm.trans hz

theorem presentedAugmentation_surjective {n : ℕ} (f : MvPolynomial (Fin n) ℂ)
    (h0 : f.coeff 0 = 0) : Function.Surjective (presentedAugmentation f h0) := by
  intro z
  exact ⟨algebraMap ℂ (PresentedRing f) z, by simp⟩

theorem presentedOriginIdeal_isMaximal {n : ℕ} (f : MvPolynomial (Fin n) ℂ)
    (h0 : f.coeff 0 = 0) : (presentedOriginIdeal f).IsMaximal := by
  rw [presentedOriginIdeal_eq_ker f h0]
  exact RingHom.ker_isMaximal_of_surjective (presentedAugmentation f h0).toRingHom
    (presentedAugmentation_surjective f h0)

end CanonicalRoots
