import CanonicalRoots.RootPowerAction

noncomputable section
namespace CanonicalRoots
open MvPolynomial

section Root
variable {n a : ℕ} (p : Fin (n + 1) → ℕ)
  (hp : AdmissibleSignature p) (ha : 1 ≤ a) (τ : DegreeGroup p) (hτ : IsCanonicalRoot p a τ)
  (N u : ℕ) (hu : 0 < u) (hN : N • τ = u • cDegree p)

/-- The box is a basis over the polynomial algebra acting by the specified powers. -/
def rootPolynomialBasis :
    letI := (rootPowerHom p τ N u hN).toRingHom.toAlgebra
    Module.Basis (RootBox p τ u) (MvPolynomial (Fin n) ℂ) (RootRing p τ) := by
  letI := (rootPowerHom p τ N u hN).toRingHom.toAlgebra
  letI := IsScalarTower.of_algHom (rootPowerHom p τ N u hN)
  exact regroupBasis (basisMonomials (Fin n) ℂ) (rootPowerBoxBasis p hp ha τ hτ N u hu hN)
    (fun q => rootPowerBoxBasis p hp ha τ hτ N u hu hN (0, q))
    (fun d q => rootPowerHom_mul_box p hp ha τ hτ N u hu hN d q)

theorem rootPolynomialBasis_apply (q : RootBox p τ u) :
    rootPolynomialBasis p hp ha τ hτ N u hu hN q =
      rootPowerBoxBasis p hp ha τ hτ N u hu hN (0, q) := by
  let := (rootPowerHom p τ N u hN).toRingHom.toAlgebra
  let := IsScalarTower.of_algHom (rootPowerHom p τ N u hN)
  exact regroupBasis_apply _ _ _ _ q

def rootBoxZero : RootBox p τ u :=
  ⟨(fun i => ⟨0, Nat.mul_pos hu (lt_of_lt_of_le (by decide) (hp.1 i.succ))⟩,
    ⟨0, lt_of_lt_of_le (by decide) (hp.1 0)⟩),
    ⟨0, by simp [boxDegree, boxExponent, Finsupp.weight_eq_sum, Fin.sum_univ_succ]⟩⟩

include hp ha hτ hu in
/-- The chosen powers are algebraically independent inside the actual root ring. -/
theorem rootPowerHom_injective : Function.Injective (rootPowerHom p τ N u hN) := by
  let := (rootPowerHom p τ N u hN).toRingHom.toAlgebra
  let b := rootPolynomialBasis p hp ha τ hτ N u hu hN
  let q := rootBoxZero p hp τ u hu
  intro x y hxy
  have he : x • b q = y • b q := by
    change rootPowerHom p τ N u hN x * b q = rootPowerHom p τ N u hN y * b q
    rw [hxy]
  have h := congrArg (fun z => b.repr z q) he
  simpa using h

include hp ha hτ hu in
theorem rootPowerGenerator_algebraicIndependent :
    AlgebraicIndependent ℂ (rootPowerGenerator p τ N u hN) :=
  rootPowerHom_injective p hp ha τ hτ N u hu hN

end Root

/-- The actual subalgebra generated by the root-degree powers. -/
def rootPowerSubalgebra {n : ℕ} (p : Fin (n + 1) → ℕ) (τ : DegreeGroup p)
    (N u : ℕ) (hN : N • τ = u • cDegree p) : Subalgebra ℂ (RootRing p τ) :=
  (rootPowerHom p τ N u hN).range

theorem rootPowerSubalgebra_eq_adjoin {n : ℕ} (p : Fin (n + 1) → ℕ) (τ : DegreeGroup p)
    (N u : ℕ) (hN : N • τ = u • cDegree p) :
    rootPowerSubalgebra p τ N u hN =
      Algebra.adjoin ℂ (Set.range (rootPowerGenerator p τ N u hN)) :=
  aeval_range _

section ActualSubalgebra
variable {n a : ℕ} (p : Fin (n + 1) → ℕ)
  (hp : AdmissibleSignature p) (ha : 1 ≤ a) (τ : DegreeGroup p) (hτ : IsCanonicalRoot p a τ)
  (N u : ℕ) (hu : 0 < u) (hN : N • τ = u • cDegree p)

def rootPowerSubalgebraEquiv :
    MvPolynomial (Fin n) ℂ ≃ₐ[ℂ] rootPowerSubalgebra p τ N u hN :=
  AlgEquiv.ofInjective (rootPowerHom p τ N u hN)
    (rootPowerHom_injective p hp ha τ hτ N u hu hN)

/-- A finite basis over the actual polynomial subalgebra of the root ring. -/
def rootFiniteFreeBasis :
    Module.Basis (RootBox p τ u) (rootPowerSubalgebra p τ N u hN) (RootRing p τ) := by
  letI := (rootPowerHom p τ N u hN).toRingHom.toAlgebra
  exact (rootPolynomialBasis p hp ha τ hτ N u hu hN).mapCoeffs
    (rootPowerSubalgebraEquiv p hp ha τ hτ N u hu hN).toRingEquiv (fun _ _ => rfl)

theorem rootFiniteFreeBasis_apply (q : RootBox p τ u) :
    rootFiniteFreeBasis p hp ha τ hτ N u hu hN q =
      rootPowerBoxBasis p hp ha τ hτ N u hu hN (0, q) := by
  let := (rootPowerHom p τ N u hN).toRingHom.toAlgebra
  exact (Module.Basis.mapCoeffs_apply (rootPolynomialBasis p hp ha τ hτ N u hu hN)
    (rootPowerSubalgebraEquiv p hp ha τ hτ N u hu hN).toRingEquiv
    (fun _ _ => rfl) q).trans (rootPolynomialBasis_apply p hp ha τ hτ N u hu hN q)

theorem rootFiniteFreeBasis_homogeneous (q : RootBox p τ u) :
    rootFiniteFreeBasis p hp ha τ hτ N u hu hN q ∈ rootPiece p τ (rootBoxDegree p τ u q) := by
  rw [rootFiniteFreeBasis_apply]
  simpa using rootPowerBoxBasis_homogeneous p hp ha τ hτ N u hu hN 0 q

include hp ha hτ hu in
theorem root_finite_over_powerSubalgebra :
    Module.Finite (rootPowerSubalgebra p τ N u hN) (RootRing p τ) :=
  Module.Finite.of_basis (rootFiniteFreeBasis p hp ha τ hτ N u hu hN)

include hp ha hτ hu in
theorem root_free_over_powerSubalgebra :
    Module.Free (rootPowerSubalgebra p τ N u hN) (RootRing p τ) :=
  Module.Free.of_basis (rootFiniteFreeBasis p hp ha τ hτ N u hu hN)

end ActualSubalgebra
end CanonicalRoots
